&lt;!-- CTA Section - With Stats --&gt;
&lt;div class=&quot;bg-white&quot;&gt;
    &lt;div class=&quot;max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8&quot;&gt;
        &lt;div class=&quot;bg-blue-700 rounded-lg shadow-xl overflow-hidden lg:grid lg:grid-cols-2 lg:gap-4&quot;&gt;
            &lt;div class=&quot;pt-10 pb-12 px-6 sm:pt-16 sm:px-16 lg:py-16 lg:pr-0 xl:py-20 xl:px-20&quot;&gt;
                &lt;div class=&quot;lg:self-center&quot;&gt;
                    &lt;h2 class=&quot;text-3xl font-bold text-white sm:text-4xl&quot;&gt;
                        &lt;span class=&quot;block&quot;&gt;Join 10,000+ companies&lt;/span&gt;
                        &lt;span class=&quot;block&quot;&gt;using our platform&lt;/span&gt;
                    &lt;/h2&gt;
                    &lt;p class=&quot;mt-4 text-lg leading-6 text-blue-200&quot;&gt;
                        Trusted by industry leaders worldwide. Start building better products with our comprehensive tools and features.
                    &lt;/p&gt;
                    &lt;a href=&quot;#&quot; class=&quot;mt-8 bg-white border border-transparent rounded-md shadow px-6 py-3 inline-flex items-center text-base font-medium text-blue-600 hover:bg-blue-50 transition duration-200&quot;&gt;
                        Start free trial
                    &lt;/a&gt;
                &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;py-8 px-6 sm:py-16 sm:px-16 lg:py-16&quot;&gt;
                &lt;div class=&quot;grid grid-cols-2 gap-4&quot;&gt;
                    &lt;div class=&quot;text-center&quot;&gt;
                        &lt;p class=&quot;text-4xl font-bold text-white&quot;&gt;10k+&lt;/p&gt;
                        &lt;p class=&quot;text-blue-200&quot;&gt;Companies&lt;/p&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;text-center&quot;&gt;
                        &lt;p class=&quot;text-4xl font-bold text-white&quot;&gt;99.9%&lt;/p&gt;
                        &lt;p class=&quot;text-blue-200&quot;&gt;Uptime&lt;/p&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;text-center&quot;&gt;
                        &lt;p class=&quot;text-4xl font-bold text-white&quot;&gt;24/7&lt;/p&gt;
                        &lt;p class=&quot;text-blue-200&quot;&gt;Support&lt;/p&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;text-center&quot;&gt;
                        &lt;p class=&quot;text-4xl font-bold text-white&quot;&gt;5★&lt;/p&gt;
                        &lt;p class=&quot;text-blue-200&quot;&gt;Rating&lt;/p&gt;
                    &lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
