&lt;!-- Footer - Simple Footer --&gt;
&lt;footer class=&quot;bg-white border-t border-gray-200&quot;&gt;
    &lt;div class=&quot;max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8&quot;&gt;
        &lt;div class=&quot;xl:grid xl:grid-cols-3 xl:gap-8&quot;&gt;
            &lt;div class=&quot;space-y-8 xl:col-span-1&quot;&gt;
                &lt;div class=&quot;flex items-center&quot;&gt;
                    &lt;div class=&quot;flex-shrink-0&quot;&gt;
                        &lt;h3 class=&quot;text-xl font-bold text-gray-900&quot;&gt;Your Logo&lt;/h3&gt;
                    &lt;/div&gt;
                &lt;/div&gt;
                &lt;p class=&quot;text-gray-500 text-base&quot;&gt;
                    Making the world a better place through constructing elegant hierarchies.
                &lt;/p&gt;
                &lt;div class=&quot;flex space-x-6&quot;&gt;
                    &lt;a href=&quot;#&quot; class=&quot;text-gray-400 hover:text-gray-500&quot;&gt;
                        &lt;span class=&quot;sr-only&quot;&gt;Facebook&lt;/span&gt;
                        &lt;svg class=&quot;h-6 w-6&quot; fill=&quot;currentColor&quot; viewBox=&quot;0 0 24 24&quot;&gt;
                            &lt;path fill-rule=&quot;evenodd&quot; d=&quot;M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z&quot; clip-rule=&quot;evenodd&quot; /&gt;
                        &lt;/svg&gt;
                    &lt;/a&gt;
                    &lt;a href=&quot;#&quot; class=&quot;text-gray-400 hover:text-gray-500&quot;&gt;
                        &lt;span class=&quot;sr-only&quot;&gt;Twitter&lt;/span&gt;
                        &lt;svg class=&quot;h-6 w-6&quot; fill=&quot;currentColor&quot; viewBox=&quot;0 0 24 24&quot;&gt;
                            &lt;path d=&quot;M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84&quot; /&gt;
                        &lt;/svg&gt;
                    &lt;/a&gt;
                &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class=&quot;mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2&quot;&gt;
                &lt;div class=&quot;md:grid md:grid-cols-2 md:gap-8&quot;&gt;
                    &lt;div&gt;
                        &lt;h3 class=&quot;text-sm font-semibold text-gray-400 tracking-wider uppercase&quot;&gt;Solutions&lt;/h3&gt;
                        &lt;ul class=&quot;mt-4 space-y-4&quot;&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Marketing&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Analytics&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Commerce&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Insights&lt;/a&gt;&lt;/li&gt;
                        &lt;/ul&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;mt-12 md:mt-0&quot;&gt;
                        &lt;h3 class=&quot;text-sm font-semibold text-gray-400 tracking-wider uppercase&quot;&gt;Support&lt;/h3&gt;
                        &lt;ul class=&quot;mt-4 space-y-4&quot;&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Pricing&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Documentation&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Guides&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;API Status&lt;/a&gt;&lt;/li&gt;
                        &lt;/ul&gt;
                    &lt;/div&gt;
                &lt;/div&gt;
                &lt;div class=&quot;md:grid md:grid-cols-2 md:gap-8&quot;&gt;
                    &lt;div&gt;
                        &lt;h3 class=&quot;text-sm font-semibold text-gray-400 tracking-wider uppercase&quot;&gt;Company&lt;/h3&gt;
                        &lt;ul class=&quot;mt-4 space-y-4&quot;&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;About&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Blog&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Jobs&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Press&lt;/a&gt;&lt;/li&gt;
                        &lt;/ul&gt;
                    &lt;/div&gt;
                    &lt;div class=&quot;mt-12 md:mt-0&quot;&gt;
                        &lt;h3 class=&quot;text-sm font-semibold text-gray-400 tracking-wider uppercase&quot;&gt;Legal&lt;/h3&gt;
                        &lt;ul class=&quot;mt-4 space-y-4&quot;&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Claim&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Privacy&lt;/a&gt;&lt;/li&gt;
                            &lt;li&gt;&lt;a href=&quot;#&quot; class=&quot;text-base text-gray-500 hover:text-gray-900&quot;&gt;Terms&lt;/a&gt;&lt;/li&gt;
                        &lt;/ul&gt;
                    &lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
        &lt;div class=&quot;mt-12 border-t border-gray-200 pt-8&quot;&gt;
            &lt;p class=&quot;text-base text-gray-400 xl:text-center&quot;&gt;
                &amp;copy; 2024 Your Company, Inc. All rights reserved.
            &lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/footer&gt;
